apiVersion: v2
name: honeybeepf-prometheus
description: A Helm chart for honeybeepf prometheus
version: 1.0.0
dependencies:
  - name: prometheus
    version: 25.8.0
    repository: https://prometheus-community.github.io/helm-charts